name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    with:
        submodules: 'true'

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset "linux-release"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset "linux-release"

    - name: Test
      run: ctest --preset "linux-release"
      
