name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Configure CMake
      run: cmake --preset "linux-release"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset "linux-release"

    - name: Test
      run: ctest --preset "linux-release"
      
